name: Test-OSX

on: push
# on:
#   schedule:
#     - cron: '0 14 * * 1'


jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        # version: [3.10] #, 3.11, 3.12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' #${{ matrix.version }}
      - name: Install
        run: pip install picture-nnunet-package --index-url https://gitlab.com/api/v4/projects/43010649/packages/pypi/simple
      - name: Test
        run: "python ./test.py"
