name: Test-OSX

on: push
# on:
#   schedule:
#     - cron: '0 14 * * 1'


jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] # windows-latest,
        # version: [3.10] #, 3.11, 3.12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' #${{ matrix.version }}
      - name: Download
        run: wget --user-agent Mozilla/4.0 'https://download.wetransfer.com/eugv/ef5c8d36a2a43816d8e0897f21ff105420231107140725/a0f79755f917657c5b5f7ca7bb2890921cba8604/picture_nnunet_package-0.4.2-py3-none-any.whl?cf=y&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRlZmF1bHQifQ.eyJleHAiOjE2OTkzNjY3MjYsImlhdCI6MTY5OTM2NjEyNiwiZG93bmxvYWRfaWQiOiI4YzVmNzdiNy02OWQ0LTRmMzUtODAxMy1hOGU3MjI4ZTdmNDgiLCJzdG9yYWdlX3NlcnZpY2UiOiJzdG9ybSJ9.TnhuiwvhjuzqeuleCUn6Skiai_bcQL5QqpommtCFnHY' -O ./picture_nnunet_package-0.4.2-py3-none-any.whl
      - name: Install
        run: pip install ./picture_nnunet_package-0.4.2-py3-none-any.whl
        # run: pip install picture-nnunet-package --index-url https://gitlab.com/api/v4/projects/43010649/packages/pypi/simple
      - name: Test
        run: "python ./test.py"
