name: Test-nnUNetPackage

on: 
  schedule:
    - cron: '0 14 * * 1'


jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        version: [3.8, 3.9, '3.10'] 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install
        # run: pip install ./picture_nnunet_package-0.4.3-py3-none-any.whl
        run: pip install picture-nnunet-package --index-url https://gitlab.com/api/v4/projects/43010649/packages/pypi/simple --no-cache
      - name: test
        run: "python ./test.py"
