jobs:
  build:
    runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install
        run: pip install picture-nnunet-package --index-url https://gitlab.com/api/v4/projects/43010649/packages/pypi/simple
      - name: Test
        run: segment_glioma ./ses-preop/NativeT1c.nii.gz --sessiontype preop
